### ISSUE TITLE
Get Http 404 error when loading TransPose-H-A4 from Torch Hub

### ISSUE THREAD

**Issue by EckoTan0804** [yangsenius/TransPose#10]
Hello.

When I tried to load TransPose-H-A4 models with pretrained weights on COCO train2017 dataset from Torch Hub, I got `HTTP Error 404: Not Found` error. It seems that the `yaml_url` in `tph_a4_256x192()` of `hubconf.py` is not valid.

**Comment by yangsenius** [comment]
Hi, @EckoTan0804.

Sorry, the YAML URL of TranPose-H-A4 was not existing. I have uploaded it now.
