### ISSUE TITLE
Unable to load the model 'tp_r_256x192_enc4_d256_h1024_mh8.pth'

### ISSUE THREAD

**Issue by NickelRaney** [yangsenius/TransPose#2]
There is an error:

=> loading model from models/pytorch/transpose_coco/tp_r_256x192_enc4_d256_h1024_mh8.pth
Traceback (most recent call last):
  File "/data3/wutianyi/anaconda3/envs/ipertest/lib/python3.7/tarfile.py", line 187, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'v2\nq\x03((X'

It seems that there is something wrong with the pth file.

**Comment by yangsenius** [comment]
Hi, @NickelRaney.  What is your PyTorch version? I recommend to use PyTorch >=1.6 to load the pre-trained models, because the pth file is saved as `zip` file by default in the new version of PyTorch (>=1.6).
