### ISSUE TITLE
no modules named nms.cpu & nms.gpu

### ISSUE THREAD

**Issue by emilyjiayaoli** [yangsenius/TransPose#20]
when running python tools/test.py --cfg experiments/coco/transpose_r/TP_R_256x192_d256_h1024_enc4_mh8.yaml TEST.USE_GT_BBOX True

File ../lib/nms/nms.py", line 13, in <module>
    from .cpu_nms import cpu_nms
ModuleNotFoundError: No module named 'nms.cpu_nms'

Only nms.cpu.c and nms.gpu.c exists in the nms folder, not nms.cpu and nms.gpu

**Comment by yangsenius** [comment]
You may need to Make the lib.

**Comment by WayneChen-cloud** [comment]
hi,
after I run Make, I still meet this error when I run the demo.ipynb:
ModuleNotFoundError: No module named 'nms.cpu_nms'
How can i deal with it?
