### ISSUE TITLE
The meaning of Head？

### ISSUE THREAD

**Issue by Nghingtim** [yangsenius/TransPose#4]
Nice work. I have a question about what is the head in the pipeline?

There are several meanings of Head: For example, one is  the multi-head in the transformer indicates the relationship between different patches; but, my understanding is that, it is the output of deconvolution, such as a 64*48 matrix which is used to calculate the heatmap loss. Is it right?

**Comment by yangsenius** [comment]
Yes. The head in the pipeline means the model part to predict keypoint heatmaps. It mainly includes a position-wise 1x1 convolution.  For TransPose-R, an additional deconvolution is used to upsample the output size. @Nghingtim

**Comment by Nghingtim** [comment]
Yes.  Deconvolution operating for head is the common practise in SimpleBaseline.
