### ISSUE TITLE
TransPoseV2?

### ISSUE THREAD

**Issue by douyh** [yangsenius/TransPose#6]
What's the difference between TransPose and TransPoseV2, which can be found in the repo release?

**Comment by yangsenius** [comment]
It is a newly updated paper. Main differences:

- We conduct new experiments on MPII dataset

- The visualization examples are visualized by TransPose-R-A4 and TransPose-H-A4 models by filtering lower attention scores with a threshold value. See details in the paper.

We will publish a new version paper on arxiv. Thanks for your attention.
