### ISSUE TITLE
Code for visualization

### ISSUE THREAD

**Issue by weixuansun** [yangsenius/TransPose#8]
Thanks for the great work, 
I wonder can you please share the code of how you visualize the attention map? or did I miss it somewhere?

**Comment by yangsenius** [comment]
Thanks for your interest~ 
The code for visualizing the attention maps is not included in the current repo. We may share it in the future.

**Comment by weixuansun** [comment]
> Thanks for your interest~
> The code for visualizing the attention maps is not included in the current repo. We may share it in the future.

Thanks, looking forward to it.
